Pages/CrashTestingProjectPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Noah_Core_Portfolio.Pages
{
    public class CrashTestingProjectPageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Noah_Core_Portfolio.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO;

namespace Noah_Core_Portfolio.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostDownloadFile()
        {
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "NoahCoreResume.pdf");
            Byte[] buffer = await System.IO.File.ReadAllBytesAsync(path);
            return File(buffer, "application/pdf");
        }
    }
}

Pages/KittyScrambleProjectPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Noah_Core_Portfolio.Pages
{
    public class KittyScrambleProjectPageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/MovieProjectPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Noah_Core_Portfolio.Pages
{
    public class MovieProjectPageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/PongProjectPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Noah_Core_Portfolio.Pages
{
    public class PongProjectPageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Projects.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Noah_Core_Portfolio.Pages
{
    public class ProjectsModel : PageModel
    {
        private readonly ILogger<ProjectsModel> _logger;

        public ProjectsModel(ILogger<ProjectsModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

Pages/CrashTestingProjectPage.cshtml
@page
@model CrashTestingProjectPageModel
@{
    ViewData["Title"] = "Crash Testing Project Page";
}

<a class="link-light" asp-area"" asp-page="/Projects">Back to Projects</a>
<h1>Crash Testing</h1>

<img class="img-fluid w-100 h-auto border" src="images/crash_testing.png" alt="Crash Testing title screen" />


<p class="pt-2">
    <i>Crash Testing</i> is an engaging game where players guide a crash-test dummy through a progressively 
    challenging array of obstacles and platforms, aiming to reach the highest point possible! This marks 
    my initial endeavor in creating a 3D platformer, during which I explored various concepts, including:
</p>
<ul>
    <li>Transforming the player character model into a ragdoll upon impact with a projectile</li>
    <li>Implementing checkpoints for player respawn</li>
    <li>Ensuring data persistence across scenes and sessions</li>
</ul>
<form action="https://noahcore.itch.io/crash-testing" target="_blank" rel="noopener noreferrer">
    <button type="submit" class="rounded-2" style="margin:auto; display:block;">Click to Play</button>
</form>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Noah Core Games";
}
<div>
    <h1>About Me</h1>
    <p>Dedicated and motivated professional with a passion for developing engaging, high-quality 
        applications, particularly in the video game sector. Possessing a solid foundation in software 
        design and development, complemented by expertise in frameworks such as ASP.NET Core and 
        proficiency in game engines like Unity. Following the completion of my bachelors degree in Computer
        Science at the University of Arkansas, I have enhanced my skill set through various side projects 
        and am now eager to contribute and grow within a team environment, aligning my efforts with the 
        objectives of the team.</p>
    <br />
    <form asp-page-handler="DownloadFile" method="post">
        <button class="rounded-2" style="margin:auto; display:block;" type="submit">Download my resume</button>
    </form>
    <!--<button class="rounded-2" type="button" style="margin:auto; display:block;">View my resume</button>-->
    <h1>My Skills</h1>
    <div class="container">
        <div class="row">
            <div class="col" style="text-align:center">
                <img src="images/programming.jpg" alt="Programming symbol" width="100" height="100" />
                <h5>Programming</h5>
                <p class="text-muted">
                    I possess a solid foundational understanding of programming techniques across a variety of 
                    languages, including C#, C++, Javascript, and Python, among others.
                </p>
            </div>
            <div class="col" style="text-align:center">
                <img src="images/netcorelogo.jpg" alt="Asp .Net Core logo" width="100" height="100" />
                <h5>ASP .NET Core</h5>
                <p class="text-muted">
                    I possess foundational experience with the ASP .Net Core framework, utilizing it to 
                    develop the frontend and backend of websites as well as establish communication 
                    with a SQL server.
                </p>
            </div>
            <div class="col" style="text-align:center">
                <img src="images/unitylogo.png" alt="Unity logo" width="100" height="100" />
                <h5 style="white-space:nowrap">Unity Game Engine</h5>
                <p class="text-muted" style="margin:auto">
                    I possess a fundamental understanding of designing, developing, and releasing 
                    games utilizing the Unity Game Engine.
                </p>
            </div>
        </div>
    </div>
</div>

Pages/KittyScrambleProjectPage.cshtml
@page
@model KittyScrambleProjectPageModel
@{
    ViewData["Title"] = "Kitty Scramble Project Page";
}
<a class="link-light" asp-area"" asp-page="/Projects">Back to Projects</a>
<h1>Kitty Scramble</h1>
<img class="img-fluid w-100 h-auto border"src="images/kitty_game.png" alt="Kitty Scramble title screen" />

<p class="pt-2">
    <i>Kitty Scramble</i> is a small top-down arcade survival game I developed while learning Unity. 
    In this game, players assume the role of a stray kitten during a zombie apocalypse. The objective 
    is to evade an unending swarm of zombies for as long as possible.
</p>
<p>
    This was one of the first games I ever created, so my primary objective was to practice basic
    fundamentals of game design. Here are some examples of the concepts I worked:
</p>
<ul>
    <li>Player control</li>
    <li>A choice of difficulty levels</li>
    <li>Particle and sound effects</li>
    <li>Interactive UI</li>
    <li>Special abilities that recharge over time</li>
</ul>

<form action="https://noahcore.itch.io/kitty-scramble" target="_blank" rel="noopener noreferrer">
    <button class="rounded-2" type="submit" style="margin:auto; display:block;">Click to Play</button>
</form>

Pages/MovieProjectPage.cshtml
@page
@model MovieProjectPageModel
@{
    ViewData["Title"] = "Movie Theater Project Page";
}
<a class="link-light" asp-area"" asp-page="/Projects">Back to Projects</a>
<h1>Movie Theater Website Project</h1>
<img class="img-fluid w-100 h-auto" src="images/MovieTheaterProject.png" alt="Movie Theater Project home screen" />

<p class="p-2">
    In this project I developed a full-stack web application that simulates the website of a movie theater, 
    built using the ASP.NET Core MVC (Model–View–Controller) framework. My goal was to demonstrate 
    a strong understanding of the framework by separating presentation, application logic, and data 
    handling. I implemented full CRUD functionality for the Movies and Auditoriums models, allowing users 
    to create, view, update, and delete entries directly through the UI. The application also allows 
    users to assign selected movies to specific auditoriums, as in real life theater scheduling.
    <br />
    The application's data is managed and persisted through an integrated SQL database, with which 
    communication is achieved through LINQ-based queries and strongly-typed models. The database is accessed 
    exclusively through a dedicated Business Object Layer to ensure secure, maintainable communication 
    and to prevent Controllers from directly interacting with the database.
    <br />
    This project highlights my ability to build data-driven web applications, design relational data 
    models, and create seamless communication between an MVC application and a SQL database. It also 
    reflects my practical experience with backend integration and structured application development 
    within ASP .NET Core.
</p>

<form action="https://github.com/ForgetfulLlama/Movie-Theater-Project" target="_blank" rel="noopener noreferrer">
    <button class="rounded-2" type="submit" style="margin:auto; display:block;">View my code</button>
</form>

Pages/PongProjectPage.cshtml
@page
@model PongProjectPageModel
@{
    ViewData["Title"] = "Pong Project Page";
}
<a class="link-light" asp-area"" asp-page="/Projects">Back to Projects</a>
<h1>Pong Recreation</h1>
<img class="img-fluid w-100 h-auto border" src="images/pong.png" alt="Pong screenshot" />
<br />

<p class="pt-2">
    In this project, I aimed to replicate the iconic video game <i>Pong</i>. It was the one of the first projects 
    I undertook while learning to use Unity, and I continued to develop it alongside my studies.
    As a result, the <i>Pong</i> project served as a continuous 'checkpoint' for me to assess how I
    could implement my newfound knowledge. Some of the skills I developed while working on this
    project are: 
</p>
<ul>
    <li>
        Simulating fundamental physics interactions, such as determining the launch trajectory 
        of a ball post-collision with a paddle.
    </li>
    <li>Developing a computer-controlled opponent to enable single-player gameplay</li>
</ul>
<form action="https://noahcore.itch.io/pong" target="_blank" rel="noopener noreferrer">
    <button class="rounded-2" type="submit" style="margin:auto; display:block;">Click to Play</button>
</form>

Pages/Projects.cshtml
@page
@model ProjectsModel
@{
    ViewData["Title"] = "Projects";
}
<h1>@ViewData["Title"]</h1>

<style>
    div.game-preview{border-style: ridge; margin-top:10px; margin-bottom:10px}
    a.title-link{color: white; text-decoration: none;}
    a.title-link:hover{color: blue; text-decoration: underline}
</style>

<div class="container">
    <div class="row">
        <div class="col game-preview text-center">
            <a asp-area="" asp-page="/CrashTestingProjectPage" class="title-link">
                <img src="images/crash_testing.png" alt="Crash Testing title screen" width="200" height="150"/>
                <p class="text-center">Crash Testing</p>
            </a>
        </div>        
        <div class="col game-preview text-center">
            <a asp-area="" asp-page="/PongProjectPage" class="title-link">
                <img src="images/pong.png" alt="Pong title screen" width="200" height="150" />
                <p class="text-center">Pong recreation</p>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col game-preview text-center">
            <a asp-area="" asp-page="/KittyScrambleProjectPage" class="title-link">
                <img src="images/kitty_game.png" alt="Kitty Scramble title screen" width="200" height="150" />
                <p class="text-center">Kitty Scramble</p>
            </a>
        </div>
        <div class="col game-preview text-center">
            <a asp-area="" asp-page="/MovieProjectPage" class="title-link">
                <img src="images/MovieTheaterProject.png" alt="Movie Theater Project Home Screen" width="200" height="150" />
                <p class="text-center">Movie Theater Website Project</p>
            </a>
        </div>
    </div>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Noah Core Portfolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Noah_Core_Portfolio.styles.css" asp-append-version="true" />
    <style>
        body{
            background-color: gray;
            color: white;
        }
        .main_body{
            border: 15px solid black;
            border-radius: 25px;
            background-color:black;
        }

        .profile{
            border-right: 5px solid grey;
            
        }
    </style>
</head>
<body style="max-height:300px">
    <header>
        <nav class="navbar navbar-expand-sm bg-black navbar-toggleable-sm navbar-dark box-shadow mb-1">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index" style="font-size:30px">Noah Core Portfolio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-page="/Projects">Projects</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container main_body">
        <div class="row" style="height:77vh;overflow-y:hidden;">
            <div class="col text-center profile h-100 overflow-auto">
                <img class="rounded-2" src="images/profile_pic.jpg" alt="Picture of myself" height="200" width="150"/>
                <h3 class="display-4" title="test">Noah Core</h3>
                <p>
                    Software & Game Developer<br />
                    <a href="mailto:noah47759@gmail.com">noah47759@gmail.com</a>
                </p>
                <div class="row">
                    <div class="col text-end">
                        <a href="https://github.com/ForgetfulLlama" target="_blank" rel="noopener noreferrer">
                            <img class="w-25 h-auto" src="images/Github_logo.webp" alt="Github logo" style="background-color:white"/>
                        </a>
                        <p>Github</p>
                    </div>
                    <div class="col">
                        <a href="https://www.linkedin.com/in/noah-core-2aa1a12a1" target="_blank" rel="noopener noreferrer">
                            <img class="w-25 h-auto" src="images/LinkedIn_logo.png" alt="LinkedIn logo" />
                        </a>
                        <p>LinkedIn</p>
                    </div>
                    <div class="col text-start">
                        <a href="https://noahcore.itch.io/" target="_blank" rel="noopener noreferrer">
                            <img class="w-25 h-auto" src="images/itchio_logo.png" alt="Itch.io logo" />
                        </a>
                        <p>Itch.io</p>
                    </div>
                </div>
            </div>
            <div class="col pb-3 h-100 overflow-auto">
                <main role="main">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <footer class="footer text-muted bg-black" style="margin-top:5px;box-shadow: 0 50vh 0 50vh black;">
        <div class="container">
            &copy; 2025 - Noah Core Portfolio
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>